services:
  app:
    build:
      context: ./app
      target: dev
    restart: always
    volumes:
      - /app/node_modules
      - ./app:/app
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      target: dev
    restart: always
    volumes:
      - /client/node_modules
      - ./client:/client
      - ./app/models:/app/models:ro
      - ./app/node_modules:/app/node_modules:ro
      - /app/.next
    environment:
      - TZ=America/Los_Angeles
      - WATCHPACK_POLLING=true
      - NODE_PATH=/app/node_modules:/client/node_modules
    ports:
      - "3000:3000"
