services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./app:/app
    environment:
      - TZ=America/Los_Angeles

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /client/node_modules
      - ./client:/client
      - /app/.next
    environment:
      - TZ=America/Los_Angeles
      - WATCHPACK_POLLING=true
      - API_URL=http://app:8000

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
