services:
  client:
    build:
      context: ./client
      target: dev
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - TZ=America/Los_Angeles
      - API_URL=http://host.docker.internal:8080
      - API_KEY=${API_KEY}
    ports:
      - "3000:3000"
