name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-unit-tests:
    uses: ./.github/workflows/backend-unit-tests.yml
    secrets: inherit
  
  frontend-unit-tests:
    uses: ./.github/workflows/frontend-unit-tests.yml
    secrets: inherit

  deploy:
    needs: backend-unit-tests
    uses: ./.github/workflows/push-to-ecr.yml
    secrets: inherit
