name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-unit-tests:
    uses: ./.github/workflows/backend-unit-tests.yml
    secrets: inherit

  frontend-unit-tests:
    uses: ./.github/workflows/frontend-unit-tests.yml
    secrets: inherit

  push-backend-image:
    needs: backend-unit-tests
    uses: ./.github/workflows/push-to-ecr.yml
    secrets: inherit
    with:
      image-tag: "backend-${{ github.sha }}"
      layer: "app"

  push-frontend-image:
    needs: frontend-unit-tests
    uses: ./.github/workflows/push-to-ecr.yml
    secrets: inherit
    with:
      image-tag: "frontend-${{ github.sha }}"
      layer: "client"

  push-nginx-image:
    needs:
      - push-backend-image
      - push-frontend-image
    uses: ./.github/workflows/push-to-ecr.yml
    secrets: inherit
    with:
      image-tag: "nginx-${{ github.sha }}"
      layer: "nginx"

  deploy:
    runs-on: ubuntu-latest
    needs: push-nginx-image
    steps:
      - name: Execute commands via SSM
        id: execute_command
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["echo \"Commands to be executed\"",
                                    "whoami"]' \
            --comment "Deploying comment" \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"
          echo "::set-output name=command_id::$COMMAND_ID"
