name: Update Version in page.tsx on Release

on:
  push:
    branches: 
      - Add-version-to-page-(#102)

permissions:
  contents: write  # Required to commit and push changes

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest Git tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $TAG"
          # Remove 'v' and split into components
          VERSION=${TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # Bump the minor version and reset patch to 0
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="v$MAJOR.$NEW_MINOR.0"

          echo "OLD_VERSION=$TAG" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update version in page.tsx
        run: |
          FILE="client/src/app/page.tsx"
          OLD_VERSION_LINE=$(grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+' "$FILE")

          echo "Replacing: $OLD_VERSION_LINE, with: $NEW_VERSION"
          sed -i "s/$OLD_VERSION_LINE/$NEW_VERSION/" "$FILE"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add client/src/app/page.tsx
          git commit -m "chore: update version on page to $NEW_VERSION"
          git push origin HEAD:"Add-version-to-page-(#102)"
